# Development environment values for the Real Estate Helm chart

replicaCount: 1

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: mayorstacks/real-estate-backend
  tag: v1.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  name: real-estate-api-service

ingress:
  enabled: true
  name: real-estate-ingress
  host: estate.mayorstacks.work # remove this later
  tlsSecretName: api-estate-tls
  clusterIssuer: "letsencrypt-staging"

namespace: dev-real-estate

config:
  ginMode: debug # Development mode uses "debug" for the GIN framework

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
