apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: real-estate-backend-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AppcraftHQ/k8s-api-deployment
    targetRevision: main
    path: infra/helm/real-estate-chart
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-real-estate

  syncPolicy:
    # Enable automatic sync
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false # Prevent deleting all resources
