# Grafana admin login credentials — stored at /grafana_admin in Infisical

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-admin-infisical-secret
  namespace: monitoring
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        envSlug: "dev"
        secretsPath: "/grafana_admin"
        projectSlug: "job-board-project-qdsi"
      credentialsRef:
        secretName: infisical-auth-monitoring
        secretNamespace: monitoring
  managedSecretReference:
    secretName: grafana-admin-secret
    secretNamespace: monitoring
    secretType: Opaque
    creationPolicy: "Owner"
  resyncInterval: 300
---
# Grafana Telegram bot credentials — stored at /grafana_telegram in Infisical
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-telegram-infisical-secret
  namespace: monitoring
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        envSlug: "dev"
        secretsPath: "/grafana_telegram"
        projectSlug: "job-board-project-qdsi"
      credentialsRef:
        secretName: infisical-auth-monitoring
        secretNamespace: monitoring
  managedSecretReference:
    secretName: grafana-telegram-secret
    secretNamespace: monitoring
    secretType: Opaque
    creationPolicy: "Owner"
  resyncInterval: 300
